name: Deploy Next App to S3

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - frontend-app/**
jobs:
  deploy_next:
    runs-on: ubuntu-latest
    steps:
      # checkout actions repo to setup Node.js
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Configure AWS credentials for S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Configure AWS credentials using credentials stored in GitHub secrets,
          # GitHub > Settings > Secrets.
          # programmatic access, AmazonS3FullAccess
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
          aws-region: ap-southeast-1
      # install npm dependencies on CI
      - name: npm install
        working-directory: frontend-app
        env:
          CI: true
        run:
          npm ci
      - name: deploy
        working-directory: frontend-app
        run: |
          next build
          next deploy
          aws s3 sync out s3://www.spreadjoy.sg/
