name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      # checkout actions repo to setup Node.js
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm' # experiment caching package dependencies
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Configure AWS credentials using credentials stored in GitHub secrets, 
          # GitHub > Settings > Secrets.
          # programmatic access, AWSLambda_FullAccess
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      # install npm dependencies on CI
      - name: npm install
        env:
          CI: true
        run:
          npm ci
      # compile ts to js using ncc,
      # zip and place file into ./dist/ folder
      # update-function-code on lambda function
      - name: deploy
        run: |
          npx ncc build index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=gift-redemption --zip-file=fileb://deploy.zip
